random_seed: 42

data:
  n_per_class: 100
  start: '2022-01-01'
  end: '2024-12-31'
  add_label_noise: false
  noise_rate: 0.05

vectorizers:
  tfidf:
    min_df: 2
    max_df: 0.95
    ngram_range: [1, 2]
  glove:
    model: glove-wiki-gigaword-50
  openai:
    model: text-embedding-3-small
    batch_size: 128
  sbert:
    model: all-MiniLM-L6-v2

cluster:
  algorithm: kmeans   # honored unless overridden by --clusterer
  k: 4

reduce:
  method: umap        # honored unless overridden by --reduce
  n_components: 2     # used by both UMAP and PCA
  n_neighbors: 10     # UMAP only

llm_label:
  model: gpt-4.1-nano-2025-04-14
  prompt_style: zero   # options: zero, extended
